# Generated by Django 3.0 on 2019-12-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0002_name_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='boy',
            field=models.BooleanField(default=True),
        ),
    ]
