# Generated by Django 3.0 on 2020-01-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0003_auto_20200104_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='rating',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
