# Generated by Django 3.0 on 2020-01-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0004_auto_20200105_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='rating',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
